---
# edit /etc/hosts

- name: Read entries from file                                         
  set_fact:                                                            
    entries_content: "{{ lookup('file', entries_file) | split('\n') }}"
                                                                       
- name: Add each entry to /etc/hosts                                   
  lineinfile:                                                          
    path: /etc/hosts                                                   
    line: "{{ item }}"                                                 
    state: present                                                     
  loop: "{{ entries_content }}"                                        
                                    

# edit /etc/hosts end