---
# edit /etc/hosts

- name: Read entries from file                                         
  ansible.builtin.set_fact:                                                            
    entries_content: "{{ lookup('file', entries_file) | split('\n') }}"
                                                                       
- name: Add each entry to /etc/hosts                                   
  ansible.builtin.lineinfile:                                                          
    path: /etc/hosts                                                   
    line: "{{ item }}"                                                 
    state: present                                                     
  loop: "{{ entries_content }}"                                        
                                    
# edit /etc/hosts end

- name: update cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install mc
  ansible.builtin.apt:
    name: mc
    state: present

- name: install mdadm
  ansible.builtin.apt:
    name: mdadm
    state: present

- name: install lshw
  ansible.builtin.apt:
    name: lshw
    state: present

- name: install parted
  ansible.builtin.apt:
    name: parted
    state: present