---
# tasks file for pve_update_vm

- name: install qemu agent
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 7200
    name: qemu-guest-agent
    state: latest
  notify: reboot vm

- name: install updates
  ansible.builtin.apt:
    upgrade: yes

