---
#- name: work on proxmox - update images
#  hosts: proxmox_root
#  gather_facts: 0
#  roles:
#    - role: pve_load_images
#      hosts: proxmox_root
#      tags: [never, init]

- name: work on proxmox - create vm s233 astra
  hosts: proxmox_root
  gather_facts: 0
  vars:
    vm_last_octet: 233
    img_alias: astra
    add_disks: 0
    add_disks_size: 0
  roles:
    - role: pve_create_vm
      hosts: proxmox_root
      tags: [never, init, restore]

- name: work on proxmox - create vm s234 astra
  hosts: proxmox_root
  gather_facts: 0
  vars:
    vm_last_octet: 234
    img_alias: astra
    add_disks: 0
    add_disks_size: 0
  roles:
    - role: pve_create_vm
      hosts: proxmox_root
      tags: [never, init, restore]


- name: work on - vm initial settings
  hosts: wh22_astra
  gather_facts: 1
  become: true
  roles:
    - role: pve_update_vm
    - role: prepare_server
    - role: ipv6_disable
  tags: [never, init]

- name: work on vm - rename hosts
  hosts: wh22_astra
  gather_facts: 1
  become: true
  roles:

    - { role: rename_host, old_hostname: "s233", new_hostname: "vpn1" }
    - { role: rename_host, old_hostname: "s234", new_hostname: "vpn2" }
  tags: [never, init]

