---
- name: work on proxmox - update images
  hosts: proxmox_root
  gather_facts: 0
  roles:
    - role: pve_load_images
      hosts: proxmox_root
      tags: [never, init]

- name: work on proxmox - create vm s231 astra
  hosts: proxmox_root
  gather_facts: 0
  vars:
    vm_last_octet: 231
    img_alias: astra
    add_disks: 0
    add_disks_size: 0
  roles:
    - role: pve_create_vm
      hosts: proxmox_root
      tags: [never, init, restore]

- name: work on proxmox - create vm s232 astra
  hosts: proxmox_root
  gather_facts: 0
  vars:
    vm_last_octet: 232
    img_alias: astra
    add_disks: 0
    add_disks_size: 0
  roles:
    - role: pve_create_vm
      hosts: proxmox_root
      tags: [never, init, restore]

- name: work on nfs server
  hosts: nfss
  gather_facts: 0
  become: true
  vars:
    nfs_root: "/srv/share"
    nfs_share: "upload"
    nfs_client: "192.168.1.232"
  roles:
    - role: pve_update_vm
    - role: prepare_server
    - role: nfs-server_install
    - role: nfs-server_export
  tags: [never, init]

- name: work on nfs client
  hosts: nfsc
  gather_facts: 0
  become: true
  vars:
    nfs_root: "/srv/share"
    #nfs_share: "upload"
    nfs_server: "192.168.1.231"
  roles:
    - role: pve_update_vm
    - role: prepare_server
    - role: nfs-client_install
    - role: nfs-client_mount
  tags: [never, init]



