---
# tasks file for software-distribution
- name: install software
  ansible.builtin.dnf:
    update_cache: yes
    name:
      - wget
      - rpmdevtools
      - rpm-build
      - createrepo
      - yum-utils
      - cmake
      - gcc
      - git
      - nano

    state: present
  when: ansible_facts['os_family'] == "RedHat"