---
# tasks file for openvpn_install
- name: update cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Astra Linux"

- name: install openvpn
  ansible.builtin.apt:
    name: openvpn
    state: present
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "Astra Linux"
